### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by lonngxiang** [lyz1810/live2dSpeek#3]
GET /js/pixi.min.js.map" Error (404): "Not found"
![image](https://github.com/user-attachments/assets/af4c21b1-a3ea-4642-ac49-1a583fd8252b)
另外点击说话没反应，测试音频有声音
![image](https://github.com/user-attachments/assets/f5d5c486-1eb3-4aac-80c6-5fc83373280a)

**Comment by lyz1810** [comment]
这个报错是不影响的
开始说话不能用，是因为还需要运行一个后台
后台项目地址：https://github.com/lyz1810/edge-tts
